FILESEXTRAPATHS:prepend := "${THISDIR}/files:"

DESCRIPTION = "Install modified xorg.conf fragment to fixup incorrect path generated by kirkstone"
SRC_URI = "file://updatedevice.conf"

FILES:${PN} += "${sysconfdir}/X11/xorg.conf.d/*"

do_install:append() {
	install -d ${D}${sysconfdir}/X11/xorg.conf.d/
	install -m 0644 ${WORKDIR}/updatedevice.conf ${D}${sysconfdir}/X11/xorg.conf.d/
}
